# Cleans up the template project

name: Template Janitor

on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  template-setup:
    if: github.event.repository.is_template == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Get Project Information
        run: |
          echo "NEW_ORG=${{ github.repository_owner }}" >> $GITHUB_ENV
          echo "NEW_PROJ=${{ github.event.repository.name }}" >> $GITHUB_ENV
          echo "NEW_URL=${{ github.repositoryUrl }}" >> $GITHUB_ENV
          echo "IS_TEMPLATE=${{github.event.repository.is_template}}" >> $GITHUB_ENV

      - name: Check Project Name
        run: |
          SAFE_PROJECT_NAME=$(echo ${{ env.NEW_PROJ }} | sed "s/-/_/g" | sed "s/\./_/g" )
          echo "SAFE_PROJECT_NAME=$SAFE_PROJECT_NAME" >> $GITHUB_ENV

      - name: Create Project From Template
        run: |
          # rename the CMake Project to match this project
          find apps -type f -exec sed -i "s/sdl_template/${{ env.SAFE_PROJECT_NAME }}/gi" CMakeLists.txt {} +
          
          mv apps/sdl_template apps/${{ env.SAFE_PROJECT_NAME }}
          
          # fill in placeholder for URL
          find apps -type f -exec sed -i "s|%%url%%|https://github.com/${{ env.NEW_ORG }}/${{ env.NEW_PROJ }}|gi" CMakeLists.txt {} +

      - name: Clean Up
        run: |
          rm .github/workflows/template-janitor.yml

      - uses: EndBug/add-and-commit@v9
        with:
          add: '-A'
          author_name: Template Janitor
          message: Cleanup template
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
